🚨 Update API token to required for Get Result API
splathon/splathon-api pull request #50
Opened 2019-10-12 09:42 UTC by koutalou

## Why

* API Tokenが Optionalだが、基本Requiredだと思う
* Generaterの制限でもあるが、DartのOptional引数はLabelが必要でこのままだと `X_SPLATHON_API_TOKEN: token` みたいなコードを書かないといけなくてプチ辛み
* たぶんServerの実装には影響ない（必ず付くだけなので）のでRequiredにしたい

## What

* ResultApi の `X_SPLATHON_API_TOKEN` をRequired に変更した

2019-10-12 09:44 UTC, koutalou commented
いや、もしかしてこれアプリじゃない部分で叩くケースがあるのかな:eyes:

2019-10-12 10:03 UTC, haya14busa requested changes
GetResult はtokenなしでもアクセスするのでrequiredじゃないです

2019-10-12 10:05 UTC, koutalou commented
アプリは付けるようにしたけど他で叩くケースがあるってこと？

2019-10-12 10:05 UTC, koutalou commented
まぁ多少の辛みはいいか

2019-10-12 10:05 UTC, closed without merging

2019-10-19 14:42 UTC, haya14busa commented
ちな、スコアボードとかがトークンなしで使うケースがジッサイにあります